### ISSUE TITLE
Rewrite for added functionality

### ISSUE THREAD

**Issue by acstll** [juliangruber/deep-access#1]
I wanted to ask if you would consider a PR for this.
I added 'set' and 'delete' functionality to the module, maintaining the same API:

https://github.com/acstll/deep-access/commit/997550f06c7d6a53eba4800c68befe923278d96e

`deep(obj, prop)` returns the value as before, plus…
- `deep(obj, prop)` doesn't throw when path doesn't exist
- `deep(obj, prop, value)` sets a value to the specified path
- and you can "delete" props if you set them to `deep(obj, prop, undefined)`

I basically used this bit of code:

https://github.com/substack/js-traverse/blob/master/index.js#L11-L18

And I tried to keep your coding style (which is almost basically the same as mine).

/

There's a dozen modules like this on npm. But I needed exactly this for my project.

**Comment by juliangruber** [comment]
``` js
deep(obj, 'foo.bar', 'baz');
// is the same as
deep(obj, 'foo').bar = 'baz';
```

So you can make a way smaller pull request by using already defined logic.

**Comment by juliangruber** [comment]
Do you think the set function should create key paths that don't exist yet, like `mkdir -p`?

**Comment by acstll** [comment]
> Do you think the set function should create key paths that don't exist yet, like mkdir -p?

That's something I was thinking about too. Maybe the right behaviour would be to throw… I'm not sure.

About API and making it smaller. I understand.

But in the particular case I'd be using the library I also need to use the props string (keypath) as an event string.
And it's also easier to just use the string you get passed, as in

``` js
function set (keypath, value, callback) {
  deep(obj, keypath, value);
  callback(null);
}
```

instead of having to manipulate the string to do `deep(obj, 'foo')[last] = 'baz'`

**Comment by acstll** [comment]
> Do you think the set function should create key paths that don't exist yet, like mkdir -p?

How about making it optional? Using a `p` property on `deep`:

``` js
if (deep.p && !hasOwnProperty.call(obj, key)) obj[key] = {};
```

**Comment by juliangruber** [comment]
thinking about it, you should better write your own module, as this is about _accessing_, not setting.

**Comment by acstll** [comment]
No problem. I understand.
